config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:index, :new, :show, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to @list
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movies.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<body class="mt-3 pt-3">
    <div class="row">
      <div class="col-12 col-md-6 offset-md-3">
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.association :movie %>
          <%= f.input :comment%>
          <%= f.submit "submit", class:'w-100 mt-3 btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </body>

app/views/bookmarks/new.html.erb
<div class="mt-3 pt-3 ">
  <h1 class="d-flex justify-content-center">New Bookmark!</h1>
  <div class="mt-3 d-flex justify-content-center">
    <%= link_to "Back to my list", lists_path  %>
  </div>

  <%= render 'form', bookmark: @bookmark %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>

app/views/lists/_cards.html.erb
<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    Breakfast
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/lunch.jpg)">
    Lunch
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/dinner.jpg)">
    Dinner
  </div>
</div>

app/views/lists/_form.html.erb
<body class="mt-3 pt-3">
    <div class="row">
      <div class="col-12 col-md-6 offset-md-3">
        <%= simple_form_for [ @list ] do |f| %>
          <%= f.input :name, placeholder: 'Funk' %>
          <%= f.submit "submit", class:'w-100 mt-3 btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </body>

app/views/lists/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="#">
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Messages</a>
      </li>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/lists/index.html.erb
<%= render 'navbar', list: @list %>
<body>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1536440136628-849c177e76a1?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1525&q=80);">
    <h1 class="mt-3 pt-3 d-flex justify-content-center">Welcome!</h1>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6 offset-md-3">
        <div class="d-flex space-between align-items-center justify-content-between">
          <h2 class="mt-5 mb-5">My Lists</h2>
          <a href="/lists/new">
            <i class="fas fa-film mt-4 p-3 btn">Create a new movie list</i>
          </a>
        </div>

        <div class="cards" >
          <% @lists.each do |list| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1572177191856-3cde618dee1f?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjN8fG1vdmllfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60);">
          <p class="d-flex justify-content-center">
            <%= link_to list.name, list_path(list) %>
          </p>
        </div>
        <% end %>
      </div>
  </div>
</body>

app/views/lists/new.html.erb
<div class="mt-3 pt-3 ">
  <h1 class="d-flex justify-content-center">Create a new movie list...</h1>
  <div class="mt-3 d-flex justify-content-center">
    <%= link_to "Back to my list", lists_path  %>

  </div>

  <%= render 'form', list: @list %>

</div>

app/views/lists/show.html.erb
<div class="container">
  <body class="mt-3 pt-3 d-flex justify-content-center">
    <div class="col-12 col-md-6 offset-md-3">
      <h1 class="d-flex justify-content-center"><%= @list.name %></h1>
      </p>
      <p class="row d-flex justify-content-center">
        <%= link_to "Back to my list", lists_path %>
      </p>
      <p class="row d-flex justify-content-center">
      <%= link_to "Add a movie to my list", new_list_bookmark_path(@list) %>
      </p>
      <p class="row d-flex justify-content-center">
        <ul class="list-unstyled">
          <% @list.bookmarks.each do |bookmark| %>
            <li><p class="row d-flex justify-content-center"><strong><%= bookmark.movie.title %></strong></p>
              <p class="row d-flex justify-content-center"><%= bookmark.comment %></p>
              <p class="row d-flex justify-content-center"><%= link_to "DELETE BOOKMARK", bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure?" } %>
            </li>
          <% end %>
        </ul>
      </p>
    </div>
  </body>
</div>